/* soapH.h
   Generated by gSOAP 2.7.12 from webserver.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"

#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

#ifndef SOAP_TYPE_ArrayOfDeviceStatesEx
#define SOAP_TYPE_ArrayOfDeviceStatesEx (26)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfDeviceStatesEx(struct soap*, const char*, int, const ArrayOfDeviceStatesEx *, const char*);
SOAP_FMAC3 ArrayOfDeviceStatesEx * SOAP_FMAC4 soap_get_ArrayOfDeviceStatesEx(struct soap*, ArrayOfDeviceStatesEx *, const char*, const char*);
SOAP_FMAC3 ArrayOfDeviceStatesEx * SOAP_FMAC4 soap_in_ArrayOfDeviceStatesEx(struct soap*, const char*, ArrayOfDeviceStatesEx *, const char*);
SOAP_FMAC5 ArrayOfDeviceStatesEx * SOAP_FMAC6 soap_new_ArrayOfDeviceStatesEx(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOfDeviceStatesEx(struct soap*, ArrayOfDeviceStatesEx*);
SOAP_FMAC3 ArrayOfDeviceStatesEx * SOAP_FMAC4 soap_instantiate_ArrayOfDeviceStatesEx(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOfDeviceStatesEx(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__DeviceStateEx
#define SOAP_TYPE_ns1__DeviceStateEx (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__DeviceStateEx(struct soap*, const char*, int, const ns1__DeviceStateEx *, const char*);
SOAP_FMAC3 ns1__DeviceStateEx * SOAP_FMAC4 soap_get_ns1__DeviceStateEx(struct soap*, ns1__DeviceStateEx *, const char*, const char*);
SOAP_FMAC3 ns1__DeviceStateEx * SOAP_FMAC4 soap_in_ns1__DeviceStateEx(struct soap*, const char*, ns1__DeviceStateEx *, const char*);
SOAP_FMAC5 ns1__DeviceStateEx * SOAP_FMAC6 soap_new_ns1__DeviceStateEx(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__DeviceStateEx(struct soap*, ns1__DeviceStateEx*);
SOAP_FMAC3 ns1__DeviceStateEx * SOAP_FMAC4 soap_instantiate_ns1__DeviceStateEx(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__DeviceStateEx(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOfAnyType
#define SOAP_TYPE_ArrayOfAnyType (24)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfAnyType(struct soap*, const char*, int, const ArrayOfAnyType *, const char*);
SOAP_FMAC3 ArrayOfAnyType * SOAP_FMAC4 soap_get_ArrayOfAnyType(struct soap*, ArrayOfAnyType *, const char*, const char*);
SOAP_FMAC3 ArrayOfAnyType * SOAP_FMAC4 soap_in_ArrayOfAnyType(struct soap*, const char*, ArrayOfAnyType *, const char*);
SOAP_FMAC5 ArrayOfAnyType * SOAP_FMAC6 soap_new_ArrayOfAnyType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOfAnyType(struct soap*, ArrayOfAnyType*);
SOAP_FMAC3 ArrayOfAnyType * SOAP_FMAC4 soap_instantiate_ArrayOfAnyType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOfAnyType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOfString
#define SOAP_TYPE_ArrayOfString (23)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfString(struct soap*, const char*, int, const ArrayOfString *, const char*);
SOAP_FMAC3 ArrayOfString * SOAP_FMAC4 soap_get_ArrayOfString(struct soap*, ArrayOfString *, const char*, const char*);
SOAP_FMAC3 ArrayOfString * SOAP_FMAC4 soap_in_ArrayOfString(struct soap*, const char*, ArrayOfString *, const char*);
SOAP_FMAC5 ArrayOfString * SOAP_FMAC6 soap_new_ArrayOfString(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOfString(struct soap*, ArrayOfString*);
SOAP_FMAC3 ArrayOfString * SOAP_FMAC4 soap_instantiate_ArrayOfString(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOfString(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOfDeviceStateVariable
#define SOAP_TYPE_ArrayOfDeviceStateVariable (22)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfDeviceStateVariable(struct soap*, const char*, int, const ArrayOfDeviceStateVariable *, const char*);
SOAP_FMAC3 ArrayOfDeviceStateVariable * SOAP_FMAC4 soap_get_ArrayOfDeviceStateVariable(struct soap*, ArrayOfDeviceStateVariable *, const char*, const char*);
SOAP_FMAC3 ArrayOfDeviceStateVariable * SOAP_FMAC4 soap_in_ArrayOfDeviceStateVariable(struct soap*, const char*, ArrayOfDeviceStateVariable *, const char*);
SOAP_FMAC5 ArrayOfDeviceStateVariable * SOAP_FMAC6 soap_new_ArrayOfDeviceStateVariable(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOfDeviceStateVariable(struct soap*, ArrayOfDeviceStateVariable*);
SOAP_FMAC3 ArrayOfDeviceStateVariable * SOAP_FMAC4 soap_instantiate_ArrayOfDeviceStateVariable(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOfDeviceStateVariable(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOfMessageEvent
#define SOAP_TYPE_ArrayOfMessageEvent (21)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfMessageEvent(struct soap*, const char*, int, const ArrayOfMessageEvent *, const char*);
SOAP_FMAC3 ArrayOfMessageEvent * SOAP_FMAC4 soap_get_ArrayOfMessageEvent(struct soap*, ArrayOfMessageEvent *, const char*, const char*);
SOAP_FMAC3 ArrayOfMessageEvent * SOAP_FMAC4 soap_in_ArrayOfMessageEvent(struct soap*, const char*, ArrayOfMessageEvent *, const char*);
SOAP_FMAC5 ArrayOfMessageEvent * SOAP_FMAC6 soap_new_ArrayOfMessageEvent(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOfMessageEvent(struct soap*, ArrayOfMessageEvent*);
SOAP_FMAC3 ArrayOfMessageEvent * SOAP_FMAC4 soap_instantiate_ArrayOfMessageEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOfMessageEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOfDeviceStates
#define SOAP_TYPE_ArrayOfDeviceStates (20)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfDeviceStates(struct soap*, const char*, int, const ArrayOfDeviceStates *, const char*);
SOAP_FMAC3 ArrayOfDeviceStates * SOAP_FMAC4 soap_get_ArrayOfDeviceStates(struct soap*, ArrayOfDeviceStates *, const char*, const char*);
SOAP_FMAC3 ArrayOfDeviceStates * SOAP_FMAC4 soap_in_ArrayOfDeviceStates(struct soap*, const char*, ArrayOfDeviceStates *, const char*);
SOAP_FMAC5 ArrayOfDeviceStates * SOAP_FMAC6 soap_new_ArrayOfDeviceStates(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOfDeviceStates(struct soap*, ArrayOfDeviceStates*);
SOAP_FMAC3 ArrayOfDeviceStates * SOAP_FMAC4 soap_instantiate_ArrayOfDeviceStates(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOfDeviceStates(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__DeviceStateVariable
#define SOAP_TYPE_ns1__DeviceStateVariable (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__DeviceStateVariable(struct soap*, const char*, int, const ns1__DeviceStateVariable *, const char*);
SOAP_FMAC3 ns1__DeviceStateVariable * SOAP_FMAC4 soap_get_ns1__DeviceStateVariable(struct soap*, ns1__DeviceStateVariable *, const char*, const char*);
SOAP_FMAC3 ns1__DeviceStateVariable * SOAP_FMAC4 soap_in_ns1__DeviceStateVariable(struct soap*, const char*, ns1__DeviceStateVariable *, const char*);
SOAP_FMAC5 ns1__DeviceStateVariable * SOAP_FMAC6 soap_new_ns1__DeviceStateVariable(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__DeviceStateVariable(struct soap*, ns1__DeviceStateVariable*);
SOAP_FMAC3 ns1__DeviceStateVariable * SOAP_FMAC4 soap_instantiate_ns1__DeviceStateVariable(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__DeviceStateVariable(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__MessageEvent
#define SOAP_TYPE_ns1__MessageEvent (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__MessageEvent(struct soap*, const char*, int, const ns1__MessageEvent *, const char*);
SOAP_FMAC3 ns1__MessageEvent * SOAP_FMAC4 soap_get_ns1__MessageEvent(struct soap*, ns1__MessageEvent *, const char*, const char*);
SOAP_FMAC3 ns1__MessageEvent * SOAP_FMAC4 soap_in_ns1__MessageEvent(struct soap*, const char*, ns1__MessageEvent *, const char*);
SOAP_FMAC5 ns1__MessageEvent * SOAP_FMAC6 soap_new_ns1__MessageEvent(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__MessageEvent(struct soap*, ns1__MessageEvent*);
SOAP_FMAC3 ns1__MessageEvent * SOAP_FMAC4 soap_instantiate_ns1__MessageEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__MessageEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__DeviceState
#define SOAP_TYPE_ns1__DeviceState (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__DeviceState(struct soap*, const char*, int, const ns1__DeviceState *, const char*);
SOAP_FMAC3 ns1__DeviceState * SOAP_FMAC4 soap_get_ns1__DeviceState(struct soap*, ns1__DeviceState *, const char*, const char*);
SOAP_FMAC3 ns1__DeviceState * SOAP_FMAC4 soap_in_ns1__DeviceState(struct soap*, const char*, ns1__DeviceState *, const char*);
SOAP_FMAC5 ns1__DeviceState * SOAP_FMAC6 soap_new_ns1__DeviceState(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__DeviceState(struct soap*, ns1__DeviceState*);
SOAP_FMAC3 ns1__DeviceState * SOAP_FMAC4 soap_instantiate_ns1__DeviceState(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__DeviceState(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, const xsd__string *, const char*);
SOAP_FMAC3 xsd__string * SOAP_FMAC4 soap_get_xsd__string(struct soap*, xsd__string *, const char*, const char*);
SOAP_FMAC3 xsd__string * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, xsd__string *, const char*);
SOAP_FMAC5 xsd__string * SOAP_FMAC6 soap_new_xsd__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__string(struct soap*, xsd__string*);
SOAP_FMAC3 xsd__string * SOAP_FMAC4 soap_instantiate_xsd__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__long
#define SOAP_TYPE_xsd__long (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__long(struct soap*, const char*, int, const xsd__long *, const char*);
SOAP_FMAC3 xsd__long * SOAP_FMAC4 soap_get_xsd__long(struct soap*, xsd__long *, const char*, const char*);
SOAP_FMAC3 xsd__long * SOAP_FMAC4 soap_in_xsd__long(struct soap*, const char*, xsd__long *, const char*);
SOAP_FMAC5 xsd__long * SOAP_FMAC6 soap_new_xsd__long(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__long(struct soap*, xsd__long*);
SOAP_FMAC3 xsd__long * SOAP_FMAC4 soap_instantiate_xsd__long(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__long(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const xsd__int *, const char*);
SOAP_FMAC3 xsd__int * SOAP_FMAC4 soap_get_xsd__int(struct soap*, xsd__int *, const char*, const char*);
SOAP_FMAC3 xsd__int * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, xsd__int *, const char*);
SOAP_FMAC5 xsd__int * SOAP_FMAC6 soap_new_xsd__int(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__int(struct soap*, xsd__int*);
SOAP_FMAC3 xsd__int * SOAP_FMAC4 soap_instantiate_xsd__int(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__int(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__dateTime
#define SOAP_TYPE_xsd__dateTime (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__dateTime(struct soap*, const char*, int, const xsd__dateTime *, const char*);
SOAP_FMAC3 xsd__dateTime * SOAP_FMAC4 soap_get_xsd__dateTime(struct soap*, xsd__dateTime *, const char*, const char*);
SOAP_FMAC3 xsd__dateTime * SOAP_FMAC4 soap_in_xsd__dateTime(struct soap*, const char*, xsd__dateTime *, const char*);
SOAP_FMAC5 xsd__dateTime * SOAP_FMAC6 soap_new_xsd__dateTime(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__dateTime(struct soap*, xsd__dateTime*);
SOAP_FMAC3 xsd__dateTime * SOAP_FMAC4 soap_instantiate_xsd__dateTime(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__dateTime(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__anyType
#define SOAP_TYPE_xsd__anyType (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyType(struct soap*, const char*, int, const xsd__anyType *, const char*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_get_xsd__anyType(struct soap*, xsd__anyType *, const char*, const char*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_in_xsd__anyType(struct soap*, const char*, xsd__anyType *, const char*);
SOAP_FMAC5 xsd__anyType * SOAP_FMAC6 soap_new_xsd__anyType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__anyType(struct soap*, xsd__anyType*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_instantiate_xsd__anyType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__anyType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (95)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (94)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (91)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (89)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (88)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns1__getDeviceAvailableActions
#define SOAP_TYPE_ns1__getDeviceAvailableActions (87)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getDeviceAvailableActions(struct soap*, struct ns1__getDeviceAvailableActions *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getDeviceAvailableActions(struct soap*, const struct ns1__getDeviceAvailableActions *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getDeviceAvailableActions(struct soap*, const struct ns1__getDeviceAvailableActions *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getDeviceAvailableActions(struct soap*, const char*, int, const struct ns1__getDeviceAvailableActions *, const char*);
SOAP_FMAC3 struct ns1__getDeviceAvailableActions * SOAP_FMAC4 soap_get_ns1__getDeviceAvailableActions(struct soap*, struct ns1__getDeviceAvailableActions *, const char*, const char*);
SOAP_FMAC3 struct ns1__getDeviceAvailableActions * SOAP_FMAC4 soap_in_ns1__getDeviceAvailableActions(struct soap*, const char*, struct ns1__getDeviceAvailableActions *, const char*);
SOAP_FMAC5 struct ns1__getDeviceAvailableActions * SOAP_FMAC6 soap_new_ns1__getDeviceAvailableActions(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getDeviceAvailableActions(struct soap*, struct ns1__getDeviceAvailableActions*);
SOAP_FMAC3 struct ns1__getDeviceAvailableActions * SOAP_FMAC4 soap_instantiate_ns1__getDeviceAvailableActions(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getDeviceAvailableActions(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getDeviceAvailableActionsResponse
#define SOAP_TYPE_ns1__getDeviceAvailableActionsResponse (84)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getDeviceAvailableActionsResponse(struct soap*, struct ns1__getDeviceAvailableActionsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getDeviceAvailableActionsResponse(struct soap*, const struct ns1__getDeviceAvailableActionsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getDeviceAvailableActionsResponse(struct soap*, const struct ns1__getDeviceAvailableActionsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getDeviceAvailableActionsResponse(struct soap*, const char*, int, const struct ns1__getDeviceAvailableActionsResponse *, const char*);
SOAP_FMAC3 struct ns1__getDeviceAvailableActionsResponse * SOAP_FMAC4 soap_get_ns1__getDeviceAvailableActionsResponse(struct soap*, struct ns1__getDeviceAvailableActionsResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getDeviceAvailableActionsResponse * SOAP_FMAC4 soap_in_ns1__getDeviceAvailableActionsResponse(struct soap*, const char*, struct ns1__getDeviceAvailableActionsResponse *, const char*);
SOAP_FMAC5 struct ns1__getDeviceAvailableActionsResponse * SOAP_FMAC6 soap_new_ns1__getDeviceAvailableActionsResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getDeviceAvailableActionsResponse(struct soap*, struct ns1__getDeviceAvailableActionsResponse*);
SOAP_FMAC3 struct ns1__getDeviceAvailableActionsResponse * SOAP_FMAC4 soap_instantiate_ns1__getDeviceAvailableActionsResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getDeviceAvailableActionsResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getDeviceStateVariables
#define SOAP_TYPE_ns1__getDeviceStateVariables (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getDeviceStateVariables(struct soap*, struct ns1__getDeviceStateVariables *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getDeviceStateVariables(struct soap*, const struct ns1__getDeviceStateVariables *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getDeviceStateVariables(struct soap*, const struct ns1__getDeviceStateVariables *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getDeviceStateVariables(struct soap*, const char*, int, const struct ns1__getDeviceStateVariables *, const char*);
SOAP_FMAC3 struct ns1__getDeviceStateVariables * SOAP_FMAC4 soap_get_ns1__getDeviceStateVariables(struct soap*, struct ns1__getDeviceStateVariables *, const char*, const char*);
SOAP_FMAC3 struct ns1__getDeviceStateVariables * SOAP_FMAC4 soap_in_ns1__getDeviceStateVariables(struct soap*, const char*, struct ns1__getDeviceStateVariables *, const char*);
SOAP_FMAC5 struct ns1__getDeviceStateVariables * SOAP_FMAC6 soap_new_ns1__getDeviceStateVariables(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getDeviceStateVariables(struct soap*, struct ns1__getDeviceStateVariables*);
SOAP_FMAC3 struct ns1__getDeviceStateVariables * SOAP_FMAC4 soap_instantiate_ns1__getDeviceStateVariables(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getDeviceStateVariables(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getDeviceStateVariablesResponse
#define SOAP_TYPE_ns1__getDeviceStateVariablesResponse (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getDeviceStateVariablesResponse(struct soap*, struct ns1__getDeviceStateVariablesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getDeviceStateVariablesResponse(struct soap*, const struct ns1__getDeviceStateVariablesResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getDeviceStateVariablesResponse(struct soap*, const struct ns1__getDeviceStateVariablesResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getDeviceStateVariablesResponse(struct soap*, const char*, int, const struct ns1__getDeviceStateVariablesResponse *, const char*);
SOAP_FMAC3 struct ns1__getDeviceStateVariablesResponse * SOAP_FMAC4 soap_get_ns1__getDeviceStateVariablesResponse(struct soap*, struct ns1__getDeviceStateVariablesResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getDeviceStateVariablesResponse * SOAP_FMAC4 soap_in_ns1__getDeviceStateVariablesResponse(struct soap*, const char*, struct ns1__getDeviceStateVariablesResponse *, const char*);
SOAP_FMAC5 struct ns1__getDeviceStateVariablesResponse * SOAP_FMAC6 soap_new_ns1__getDeviceStateVariablesResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getDeviceStateVariablesResponse(struct soap*, struct ns1__getDeviceStateVariablesResponse*);
SOAP_FMAC3 struct ns1__getDeviceStateVariablesResponse * SOAP_FMAC4 soap_instantiate_ns1__getDeviceStateVariablesResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getDeviceStateVariablesResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getLastDevicesEvents
#define SOAP_TYPE_ns1__getLastDevicesEvents (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getLastDevicesEvents(struct soap*, struct ns1__getLastDevicesEvents *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getLastDevicesEvents(struct soap*, const struct ns1__getLastDevicesEvents *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getLastDevicesEvents(struct soap*, const struct ns1__getLastDevicesEvents *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getLastDevicesEvents(struct soap*, const char*, int, const struct ns1__getLastDevicesEvents *, const char*);
SOAP_FMAC3 struct ns1__getLastDevicesEvents * SOAP_FMAC4 soap_get_ns1__getLastDevicesEvents(struct soap*, struct ns1__getLastDevicesEvents *, const char*, const char*);
SOAP_FMAC3 struct ns1__getLastDevicesEvents * SOAP_FMAC4 soap_in_ns1__getLastDevicesEvents(struct soap*, const char*, struct ns1__getLastDevicesEvents *, const char*);
SOAP_FMAC5 struct ns1__getLastDevicesEvents * SOAP_FMAC6 soap_new_ns1__getLastDevicesEvents(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getLastDevicesEvents(struct soap*, struct ns1__getLastDevicesEvents*);
SOAP_FMAC3 struct ns1__getLastDevicesEvents * SOAP_FMAC4 soap_instantiate_ns1__getLastDevicesEvents(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getLastDevicesEvents(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getLastDevicesEventsResponse
#define SOAP_TYPE_ns1__getLastDevicesEventsResponse (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getLastDevicesEventsResponse(struct soap*, struct ns1__getLastDevicesEventsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getLastDevicesEventsResponse(struct soap*, const struct ns1__getLastDevicesEventsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getLastDevicesEventsResponse(struct soap*, const struct ns1__getLastDevicesEventsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getLastDevicesEventsResponse(struct soap*, const char*, int, const struct ns1__getLastDevicesEventsResponse *, const char*);
SOAP_FMAC3 struct ns1__getLastDevicesEventsResponse * SOAP_FMAC4 soap_get_ns1__getLastDevicesEventsResponse(struct soap*, struct ns1__getLastDevicesEventsResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getLastDevicesEventsResponse * SOAP_FMAC4 soap_in_ns1__getLastDevicesEventsResponse(struct soap*, const char*, struct ns1__getLastDevicesEventsResponse *, const char*);
SOAP_FMAC5 struct ns1__getLastDevicesEventsResponse * SOAP_FMAC6 soap_new_ns1__getLastDevicesEventsResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getLastDevicesEventsResponse(struct soap*, struct ns1__getLastDevicesEventsResponse*);
SOAP_FMAC3 struct ns1__getLastDevicesEventsResponse * SOAP_FMAC4 soap_instantiate_ns1__getLastDevicesEventsResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getLastDevicesEventsResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__invokeAction
#define SOAP_TYPE_ns1__invokeAction (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__invokeAction(struct soap*, struct ns1__invokeAction *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__invokeAction(struct soap*, const struct ns1__invokeAction *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__invokeAction(struct soap*, const struct ns1__invokeAction *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__invokeAction(struct soap*, const char*, int, const struct ns1__invokeAction *, const char*);
SOAP_FMAC3 struct ns1__invokeAction * SOAP_FMAC4 soap_get_ns1__invokeAction(struct soap*, struct ns1__invokeAction *, const char*, const char*);
SOAP_FMAC3 struct ns1__invokeAction * SOAP_FMAC4 soap_in_ns1__invokeAction(struct soap*, const char*, struct ns1__invokeAction *, const char*);
SOAP_FMAC5 struct ns1__invokeAction * SOAP_FMAC6 soap_new_ns1__invokeAction(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__invokeAction(struct soap*, struct ns1__invokeAction*);
SOAP_FMAC3 struct ns1__invokeAction * SOAP_FMAC4 soap_instantiate_ns1__invokeAction(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__invokeAction(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__invokeActionResponse
#define SOAP_TYPE_ns1__invokeActionResponse (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__invokeActionResponse(struct soap*, struct ns1__invokeActionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__invokeActionResponse(struct soap*, const struct ns1__invokeActionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__invokeActionResponse(struct soap*, const struct ns1__invokeActionResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__invokeActionResponse(struct soap*, const char*, int, const struct ns1__invokeActionResponse *, const char*);
SOAP_FMAC3 struct ns1__invokeActionResponse * SOAP_FMAC4 soap_get_ns1__invokeActionResponse(struct soap*, struct ns1__invokeActionResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__invokeActionResponse * SOAP_FMAC4 soap_in_ns1__invokeActionResponse(struct soap*, const char*, struct ns1__invokeActionResponse *, const char*);
SOAP_FMAC5 struct ns1__invokeActionResponse * SOAP_FMAC6 soap_new_ns1__invokeActionResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__invokeActionResponse(struct soap*, struct ns1__invokeActionResponse*);
SOAP_FMAC3 struct ns1__invokeActionResponse * SOAP_FMAC4 soap_instantiate_ns1__invokeActionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__invokeActionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getAllDevicesOverviewExtendedData
#define SOAP_TYPE_ns1__getAllDevicesOverviewExtendedData (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getAllDevicesOverviewExtendedData(struct soap*, struct ns1__getAllDevicesOverviewExtendedData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getAllDevicesOverviewExtendedData(struct soap*, const struct ns1__getAllDevicesOverviewExtendedData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getAllDevicesOverviewExtendedData(struct soap*, const struct ns1__getAllDevicesOverviewExtendedData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getAllDevicesOverviewExtendedData(struct soap*, const char*, int, const struct ns1__getAllDevicesOverviewExtendedData *, const char*);
SOAP_FMAC3 struct ns1__getAllDevicesOverviewExtendedData * SOAP_FMAC4 soap_get_ns1__getAllDevicesOverviewExtendedData(struct soap*, struct ns1__getAllDevicesOverviewExtendedData *, const char*, const char*);
SOAP_FMAC3 struct ns1__getAllDevicesOverviewExtendedData * SOAP_FMAC4 soap_in_ns1__getAllDevicesOverviewExtendedData(struct soap*, const char*, struct ns1__getAllDevicesOverviewExtendedData *, const char*);
SOAP_FMAC5 struct ns1__getAllDevicesOverviewExtendedData * SOAP_FMAC6 soap_new_ns1__getAllDevicesOverviewExtendedData(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getAllDevicesOverviewExtendedData(struct soap*, struct ns1__getAllDevicesOverviewExtendedData*);
SOAP_FMAC3 struct ns1__getAllDevicesOverviewExtendedData * SOAP_FMAC4 soap_instantiate_ns1__getAllDevicesOverviewExtendedData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getAllDevicesOverviewExtendedData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getAllDevicesOverviewExtendedDataResponse
#define SOAP_TYPE_ns1__getAllDevicesOverviewExtendedDataResponse (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getAllDevicesOverviewExtendedDataResponse(struct soap*, struct ns1__getAllDevicesOverviewExtendedDataResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getAllDevicesOverviewExtendedDataResponse(struct soap*, const struct ns1__getAllDevicesOverviewExtendedDataResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getAllDevicesOverviewExtendedDataResponse(struct soap*, const struct ns1__getAllDevicesOverviewExtendedDataResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getAllDevicesOverviewExtendedDataResponse(struct soap*, const char*, int, const struct ns1__getAllDevicesOverviewExtendedDataResponse *, const char*);
SOAP_FMAC3 struct ns1__getAllDevicesOverviewExtendedDataResponse * SOAP_FMAC4 soap_get_ns1__getAllDevicesOverviewExtendedDataResponse(struct soap*, struct ns1__getAllDevicesOverviewExtendedDataResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getAllDevicesOverviewExtendedDataResponse * SOAP_FMAC4 soap_in_ns1__getAllDevicesOverviewExtendedDataResponse(struct soap*, const char*, struct ns1__getAllDevicesOverviewExtendedDataResponse *, const char*);
SOAP_FMAC5 struct ns1__getAllDevicesOverviewExtendedDataResponse * SOAP_FMAC6 soap_new_ns1__getAllDevicesOverviewExtendedDataResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getAllDevicesOverviewExtendedDataResponse(struct soap*, struct ns1__getAllDevicesOverviewExtendedDataResponse*);
SOAP_FMAC3 struct ns1__getAllDevicesOverviewExtendedDataResponse * SOAP_FMAC4 soap_instantiate_ns1__getAllDevicesOverviewExtendedDataResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getAllDevicesOverviewExtendedDataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getAllDevicesOverviewData
#define SOAP_TYPE_ns1__getAllDevicesOverviewData (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getAllDevicesOverviewData(struct soap*, struct ns1__getAllDevicesOverviewData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getAllDevicesOverviewData(struct soap*, const struct ns1__getAllDevicesOverviewData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getAllDevicesOverviewData(struct soap*, const struct ns1__getAllDevicesOverviewData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getAllDevicesOverviewData(struct soap*, const char*, int, const struct ns1__getAllDevicesOverviewData *, const char*);
SOAP_FMAC3 struct ns1__getAllDevicesOverviewData * SOAP_FMAC4 soap_get_ns1__getAllDevicesOverviewData(struct soap*, struct ns1__getAllDevicesOverviewData *, const char*, const char*);
SOAP_FMAC3 struct ns1__getAllDevicesOverviewData * SOAP_FMAC4 soap_in_ns1__getAllDevicesOverviewData(struct soap*, const char*, struct ns1__getAllDevicesOverviewData *, const char*);
SOAP_FMAC5 struct ns1__getAllDevicesOverviewData * SOAP_FMAC6 soap_new_ns1__getAllDevicesOverviewData(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getAllDevicesOverviewData(struct soap*, struct ns1__getAllDevicesOverviewData*);
SOAP_FMAC3 struct ns1__getAllDevicesOverviewData * SOAP_FMAC4 soap_instantiate_ns1__getAllDevicesOverviewData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getAllDevicesOverviewData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getAllDevicesOverviewDataResponse
#define SOAP_TYPE_ns1__getAllDevicesOverviewDataResponse (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getAllDevicesOverviewDataResponse(struct soap*, struct ns1__getAllDevicesOverviewDataResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getAllDevicesOverviewDataResponse(struct soap*, const struct ns1__getAllDevicesOverviewDataResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getAllDevicesOverviewDataResponse(struct soap*, const struct ns1__getAllDevicesOverviewDataResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getAllDevicesOverviewDataResponse(struct soap*, const char*, int, const struct ns1__getAllDevicesOverviewDataResponse *, const char*);
SOAP_FMAC3 struct ns1__getAllDevicesOverviewDataResponse * SOAP_FMAC4 soap_get_ns1__getAllDevicesOverviewDataResponse(struct soap*, struct ns1__getAllDevicesOverviewDataResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getAllDevicesOverviewDataResponse * SOAP_FMAC4 soap_in_ns1__getAllDevicesOverviewDataResponse(struct soap*, const char*, struct ns1__getAllDevicesOverviewDataResponse *, const char*);
SOAP_FMAC5 struct ns1__getAllDevicesOverviewDataResponse * SOAP_FMAC6 soap_new_ns1__getAllDevicesOverviewDataResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getAllDevicesOverviewDataResponse(struct soap*, struct ns1__getAllDevicesOverviewDataResponse*);
SOAP_FMAC3 struct ns1__getAllDevicesOverviewDataResponse * SOAP_FMAC4 soap_instantiate_ns1__getAllDevicesOverviewDataResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getAllDevicesOverviewDataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getDeviceOverviewExtendedData
#define SOAP_TYPE_ns1__getDeviceOverviewExtendedData (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getDeviceOverviewExtendedData(struct soap*, struct ns1__getDeviceOverviewExtendedData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getDeviceOverviewExtendedData(struct soap*, const struct ns1__getDeviceOverviewExtendedData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getDeviceOverviewExtendedData(struct soap*, const struct ns1__getDeviceOverviewExtendedData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getDeviceOverviewExtendedData(struct soap*, const char*, int, const struct ns1__getDeviceOverviewExtendedData *, const char*);
SOAP_FMAC3 struct ns1__getDeviceOverviewExtendedData * SOAP_FMAC4 soap_get_ns1__getDeviceOverviewExtendedData(struct soap*, struct ns1__getDeviceOverviewExtendedData *, const char*, const char*);
SOAP_FMAC3 struct ns1__getDeviceOverviewExtendedData * SOAP_FMAC4 soap_in_ns1__getDeviceOverviewExtendedData(struct soap*, const char*, struct ns1__getDeviceOverviewExtendedData *, const char*);
SOAP_FMAC5 struct ns1__getDeviceOverviewExtendedData * SOAP_FMAC6 soap_new_ns1__getDeviceOverviewExtendedData(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getDeviceOverviewExtendedData(struct soap*, struct ns1__getDeviceOverviewExtendedData*);
SOAP_FMAC3 struct ns1__getDeviceOverviewExtendedData * SOAP_FMAC4 soap_instantiate_ns1__getDeviceOverviewExtendedData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getDeviceOverviewExtendedData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getDeviceOverviewExtendedDataResponse
#define SOAP_TYPE_ns1__getDeviceOverviewExtendedDataResponse (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getDeviceOverviewExtendedDataResponse(struct soap*, struct ns1__getDeviceOverviewExtendedDataResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getDeviceOverviewExtendedDataResponse(struct soap*, const struct ns1__getDeviceOverviewExtendedDataResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getDeviceOverviewExtendedDataResponse(struct soap*, const struct ns1__getDeviceOverviewExtendedDataResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getDeviceOverviewExtendedDataResponse(struct soap*, const char*, int, const struct ns1__getDeviceOverviewExtendedDataResponse *, const char*);
SOAP_FMAC3 struct ns1__getDeviceOverviewExtendedDataResponse * SOAP_FMAC4 soap_get_ns1__getDeviceOverviewExtendedDataResponse(struct soap*, struct ns1__getDeviceOverviewExtendedDataResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getDeviceOverviewExtendedDataResponse * SOAP_FMAC4 soap_in_ns1__getDeviceOverviewExtendedDataResponse(struct soap*, const char*, struct ns1__getDeviceOverviewExtendedDataResponse *, const char*);
SOAP_FMAC5 struct ns1__getDeviceOverviewExtendedDataResponse * SOAP_FMAC6 soap_new_ns1__getDeviceOverviewExtendedDataResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getDeviceOverviewExtendedDataResponse(struct soap*, struct ns1__getDeviceOverviewExtendedDataResponse*);
SOAP_FMAC3 struct ns1__getDeviceOverviewExtendedDataResponse * SOAP_FMAC4 soap_instantiate_ns1__getDeviceOverviewExtendedDataResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getDeviceOverviewExtendedDataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getDeviceOverviewData
#define SOAP_TYPE_ns1__getDeviceOverviewData (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getDeviceOverviewData(struct soap*, struct ns1__getDeviceOverviewData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getDeviceOverviewData(struct soap*, const struct ns1__getDeviceOverviewData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getDeviceOverviewData(struct soap*, const struct ns1__getDeviceOverviewData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getDeviceOverviewData(struct soap*, const char*, int, const struct ns1__getDeviceOverviewData *, const char*);
SOAP_FMAC3 struct ns1__getDeviceOverviewData * SOAP_FMAC4 soap_get_ns1__getDeviceOverviewData(struct soap*, struct ns1__getDeviceOverviewData *, const char*, const char*);
SOAP_FMAC3 struct ns1__getDeviceOverviewData * SOAP_FMAC4 soap_in_ns1__getDeviceOverviewData(struct soap*, const char*, struct ns1__getDeviceOverviewData *, const char*);
SOAP_FMAC5 struct ns1__getDeviceOverviewData * SOAP_FMAC6 soap_new_ns1__getDeviceOverviewData(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getDeviceOverviewData(struct soap*, struct ns1__getDeviceOverviewData*);
SOAP_FMAC3 struct ns1__getDeviceOverviewData * SOAP_FMAC4 soap_instantiate_ns1__getDeviceOverviewData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getDeviceOverviewData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getDeviceOverviewDataResponse
#define SOAP_TYPE_ns1__getDeviceOverviewDataResponse (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getDeviceOverviewDataResponse(struct soap*, struct ns1__getDeviceOverviewDataResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getDeviceOverviewDataResponse(struct soap*, const struct ns1__getDeviceOverviewDataResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getDeviceOverviewDataResponse(struct soap*, const struct ns1__getDeviceOverviewDataResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getDeviceOverviewDataResponse(struct soap*, const char*, int, const struct ns1__getDeviceOverviewDataResponse *, const char*);
SOAP_FMAC3 struct ns1__getDeviceOverviewDataResponse * SOAP_FMAC4 soap_get_ns1__getDeviceOverviewDataResponse(struct soap*, struct ns1__getDeviceOverviewDataResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getDeviceOverviewDataResponse * SOAP_FMAC4 soap_in_ns1__getDeviceOverviewDataResponse(struct soap*, const char*, struct ns1__getDeviceOverviewDataResponse *, const char*);
SOAP_FMAC5 struct ns1__getDeviceOverviewDataResponse * SOAP_FMAC6 soap_new_ns1__getDeviceOverviewDataResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getDeviceOverviewDataResponse(struct soap*, struct ns1__getDeviceOverviewDataResponse*);
SOAP_FMAC3 struct ns1__getDeviceOverviewDataResponse * SOAP_FMAC4 soap_instantiate_ns1__getDeviceOverviewDataResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getDeviceOverviewDataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getAvailableDevicesIDs
#define SOAP_TYPE_ns1__getAvailableDevicesIDs (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getAvailableDevicesIDs(struct soap*, struct ns1__getAvailableDevicesIDs *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getAvailableDevicesIDs(struct soap*, const struct ns1__getAvailableDevicesIDs *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getAvailableDevicesIDs(struct soap*, const struct ns1__getAvailableDevicesIDs *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getAvailableDevicesIDs(struct soap*, const char*, int, const struct ns1__getAvailableDevicesIDs *, const char*);
SOAP_FMAC3 struct ns1__getAvailableDevicesIDs * SOAP_FMAC4 soap_get_ns1__getAvailableDevicesIDs(struct soap*, struct ns1__getAvailableDevicesIDs *, const char*, const char*);
SOAP_FMAC3 struct ns1__getAvailableDevicesIDs * SOAP_FMAC4 soap_in_ns1__getAvailableDevicesIDs(struct soap*, const char*, struct ns1__getAvailableDevicesIDs *, const char*);
SOAP_FMAC5 struct ns1__getAvailableDevicesIDs * SOAP_FMAC6 soap_new_ns1__getAvailableDevicesIDs(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getAvailableDevicesIDs(struct soap*, struct ns1__getAvailableDevicesIDs*);
SOAP_FMAC3 struct ns1__getAvailableDevicesIDs * SOAP_FMAC4 soap_instantiate_ns1__getAvailableDevicesIDs(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getAvailableDevicesIDs(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getAvailableDevicesIDsResponse
#define SOAP_TYPE_ns1__getAvailableDevicesIDsResponse (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getAvailableDevicesIDsResponse(struct soap*, struct ns1__getAvailableDevicesIDsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getAvailableDevicesIDsResponse(struct soap*, const struct ns1__getAvailableDevicesIDsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getAvailableDevicesIDsResponse(struct soap*, const struct ns1__getAvailableDevicesIDsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getAvailableDevicesIDsResponse(struct soap*, const char*, int, const struct ns1__getAvailableDevicesIDsResponse *, const char*);
SOAP_FMAC3 struct ns1__getAvailableDevicesIDsResponse * SOAP_FMAC4 soap_get_ns1__getAvailableDevicesIDsResponse(struct soap*, struct ns1__getAvailableDevicesIDsResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getAvailableDevicesIDsResponse * SOAP_FMAC4 soap_in_ns1__getAvailableDevicesIDsResponse(struct soap*, const char*, struct ns1__getAvailableDevicesIDsResponse *, const char*);
SOAP_FMAC5 struct ns1__getAvailableDevicesIDsResponse * SOAP_FMAC6 soap_new_ns1__getAvailableDevicesIDsResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getAvailableDevicesIDsResponse(struct soap*, struct ns1__getAvailableDevicesIDsResponse*);
SOAP_FMAC3 struct ns1__getAvailableDevicesIDsResponse * SOAP_FMAC4 soap_instantiate_ns1__getAvailableDevicesIDsResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getAvailableDevicesIDsResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getServerTimestamp
#define SOAP_TYPE_ns1__getServerTimestamp (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getServerTimestamp(struct soap*, struct ns1__getServerTimestamp *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getServerTimestamp(struct soap*, const struct ns1__getServerTimestamp *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getServerTimestamp(struct soap*, const struct ns1__getServerTimestamp *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getServerTimestamp(struct soap*, const char*, int, const struct ns1__getServerTimestamp *, const char*);
SOAP_FMAC3 struct ns1__getServerTimestamp * SOAP_FMAC4 soap_get_ns1__getServerTimestamp(struct soap*, struct ns1__getServerTimestamp *, const char*, const char*);
SOAP_FMAC3 struct ns1__getServerTimestamp * SOAP_FMAC4 soap_in_ns1__getServerTimestamp(struct soap*, const char*, struct ns1__getServerTimestamp *, const char*);
SOAP_FMAC5 struct ns1__getServerTimestamp * SOAP_FMAC6 soap_new_ns1__getServerTimestamp(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getServerTimestamp(struct soap*, struct ns1__getServerTimestamp*);
SOAP_FMAC3 struct ns1__getServerTimestamp * SOAP_FMAC4 soap_instantiate_ns1__getServerTimestamp(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getServerTimestamp(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getServerTimestampResponse
#define SOAP_TYPE_ns1__getServerTimestampResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getServerTimestampResponse(struct soap*, struct ns1__getServerTimestampResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getServerTimestampResponse(struct soap*, const struct ns1__getServerTimestampResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getServerTimestampResponse(struct soap*, const struct ns1__getServerTimestampResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getServerTimestampResponse(struct soap*, const char*, int, const struct ns1__getServerTimestampResponse *, const char*);
SOAP_FMAC3 struct ns1__getServerTimestampResponse * SOAP_FMAC4 soap_get_ns1__getServerTimestampResponse(struct soap*, struct ns1__getServerTimestampResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getServerTimestampResponse * SOAP_FMAC4 soap_in_ns1__getServerTimestampResponse(struct soap*, const char*, struct ns1__getServerTimestampResponse *, const char*);
SOAP_FMAC5 struct ns1__getServerTimestampResponse * SOAP_FMAC6 soap_new_ns1__getServerTimestampResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getServerTimestampResponse(struct soap*, struct ns1__getServerTimestampResponse*);
SOAP_FMAC3 struct ns1__getServerTimestampResponse * SOAP_FMAC4 soap_instantiate_ns1__getServerTimestampResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getServerTimestampResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__echo
#define SOAP_TYPE_ns1__echo (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__echo(struct soap*, struct ns1__echo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__echo(struct soap*, const struct ns1__echo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__echo(struct soap*, const struct ns1__echo *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__echo(struct soap*, const char*, int, const struct ns1__echo *, const char*);
SOAP_FMAC3 struct ns1__echo * SOAP_FMAC4 soap_get_ns1__echo(struct soap*, struct ns1__echo *, const char*, const char*);
SOAP_FMAC3 struct ns1__echo * SOAP_FMAC4 soap_in_ns1__echo(struct soap*, const char*, struct ns1__echo *, const char*);
SOAP_FMAC5 struct ns1__echo * SOAP_FMAC6 soap_new_ns1__echo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__echo(struct soap*, struct ns1__echo*);
SOAP_FMAC3 struct ns1__echo * SOAP_FMAC4 soap_instantiate_ns1__echo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__echo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__echoResponse
#define SOAP_TYPE_ns1__echoResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__echoResponse(struct soap*, struct ns1__echoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__echoResponse(struct soap*, const struct ns1__echoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__echoResponse(struct soap*, const struct ns1__echoResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__echoResponse(struct soap*, const char*, int, const struct ns1__echoResponse *, const char*);
SOAP_FMAC3 struct ns1__echoResponse * SOAP_FMAC4 soap_get_ns1__echoResponse(struct soap*, struct ns1__echoResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__echoResponse * SOAP_FMAC4 soap_in_ns1__echoResponse(struct soap*, const char*, struct ns1__echoResponse *, const char*);
SOAP_FMAC5 struct ns1__echoResponse * SOAP_FMAC6 soap_new_ns1__echoResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__echoResponse(struct soap*, struct ns1__echoResponse*);
SOAP_FMAC3 struct ns1__echoResponse * SOAP_FMAC4 soap_instantiate_ns1__echoResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__echoResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (97)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (96)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (90)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerToArrayOfDeviceStateVariable
#define SOAP_TYPE_PointerToArrayOfDeviceStateVariable (80)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfDeviceStateVariable(struct soap*, ArrayOfDeviceStateVariable *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfDeviceStateVariable(struct soap*, ArrayOfDeviceStateVariable *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfDeviceStateVariable(struct soap*, const char *, int, ArrayOfDeviceStateVariable *const*, const char *);
SOAP_FMAC3 ArrayOfDeviceStateVariable ** SOAP_FMAC4 soap_get_PointerToArrayOfDeviceStateVariable(struct soap*, ArrayOfDeviceStateVariable **, const char*, const char*);
SOAP_FMAC3 ArrayOfDeviceStateVariable ** SOAP_FMAC4 soap_in_PointerToArrayOfDeviceStateVariable(struct soap*, const char*, ArrayOfDeviceStateVariable **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfMessageEvent
#define SOAP_TYPE_PointerToArrayOfMessageEvent (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfMessageEvent(struct soap*, ArrayOfMessageEvent *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfMessageEvent(struct soap*, ArrayOfMessageEvent *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfMessageEvent(struct soap*, const char *, int, ArrayOfMessageEvent *const*, const char *);
SOAP_FMAC3 ArrayOfMessageEvent ** SOAP_FMAC4 soap_get_PointerToArrayOfMessageEvent(struct soap*, ArrayOfMessageEvent **, const char*, const char*);
SOAP_FMAC3 ArrayOfMessageEvent ** SOAP_FMAC4 soap_in_PointerToArrayOfMessageEvent(struct soap*, const char*, ArrayOfMessageEvent **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfAnyType
#define SOAP_TYPE_PointerToArrayOfAnyType (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfAnyType(struct soap*, ArrayOfAnyType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfAnyType(struct soap*, ArrayOfAnyType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfAnyType(struct soap*, const char *, int, ArrayOfAnyType *const*, const char *);
SOAP_FMAC3 ArrayOfAnyType ** SOAP_FMAC4 soap_get_PointerToArrayOfAnyType(struct soap*, ArrayOfAnyType **, const char*, const char*);
SOAP_FMAC3 ArrayOfAnyType ** SOAP_FMAC4 soap_in_PointerToArrayOfAnyType(struct soap*, const char*, ArrayOfAnyType **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfDeviceStatesEx
#define SOAP_TYPE_PointerToArrayOfDeviceStatesEx (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfDeviceStatesEx(struct soap*, ArrayOfDeviceStatesEx *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfDeviceStatesEx(struct soap*, ArrayOfDeviceStatesEx *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfDeviceStatesEx(struct soap*, const char *, int, ArrayOfDeviceStatesEx *const*, const char *);
SOAP_FMAC3 ArrayOfDeviceStatesEx ** SOAP_FMAC4 soap_get_PointerToArrayOfDeviceStatesEx(struct soap*, ArrayOfDeviceStatesEx **, const char*, const char*);
SOAP_FMAC3 ArrayOfDeviceStatesEx ** SOAP_FMAC4 soap_in_PointerToArrayOfDeviceStatesEx(struct soap*, const char*, ArrayOfDeviceStatesEx **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfDeviceStates
#define SOAP_TYPE_PointerToArrayOfDeviceStates (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfDeviceStates(struct soap*, ArrayOfDeviceStates *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfDeviceStates(struct soap*, ArrayOfDeviceStates *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfDeviceStates(struct soap*, const char *, int, ArrayOfDeviceStates *const*, const char *);
SOAP_FMAC3 ArrayOfDeviceStates ** SOAP_FMAC4 soap_get_PointerToArrayOfDeviceStates(struct soap*, ArrayOfDeviceStates **, const char*, const char*);
SOAP_FMAC3 ArrayOfDeviceStates ** SOAP_FMAC4 soap_in_PointerToArrayOfDeviceStates(struct soap*, const char*, ArrayOfDeviceStates **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__DeviceStateEx
#define SOAP_TYPE_PointerToPointerTons1__DeviceStateEx (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__DeviceStateEx(struct soap*, ns1__DeviceStateEx **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__DeviceStateEx(struct soap*, ns1__DeviceStateEx **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__DeviceStateEx(struct soap*, const char *, int, ns1__DeviceStateEx **const*, const char *);
SOAP_FMAC3 ns1__DeviceStateEx *** SOAP_FMAC4 soap_get_PointerToPointerTons1__DeviceStateEx(struct soap*, ns1__DeviceStateEx ***, const char*, const char*);
SOAP_FMAC3 ns1__DeviceStateEx *** SOAP_FMAC4 soap_in_PointerToPointerTons1__DeviceStateEx(struct soap*, const char*, ns1__DeviceStateEx ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__DeviceStateEx
#define SOAP_TYPE_PointerTons1__DeviceStateEx (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__DeviceStateEx(struct soap*, ns1__DeviceStateEx *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__DeviceStateEx(struct soap*, ns1__DeviceStateEx *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__DeviceStateEx(struct soap*, const char *, int, ns1__DeviceStateEx *const*, const char *);
SOAP_FMAC3 ns1__DeviceStateEx ** SOAP_FMAC4 soap_get_PointerTons1__DeviceStateEx(struct soap*, ns1__DeviceStateEx **, const char*, const char*);
SOAP_FMAC3 ns1__DeviceStateEx ** SOAP_FMAC4 soap_in_PointerTons1__DeviceStateEx(struct soap*, const char*, ns1__DeviceStateEx **, const char*);

#ifndef SOAP_TYPE_PointerToPointerToxsd__anyType
#define SOAP_TYPE_PointerToPointerToxsd__anyType (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerToxsd__anyType(struct soap*, xsd__anyType **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerToxsd__anyType(struct soap*, xsd__anyType **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerToxsd__anyType(struct soap*, const char *, int, xsd__anyType **const*, const char *);
SOAP_FMAC3 xsd__anyType *** SOAP_FMAC4 soap_get_PointerToPointerToxsd__anyType(struct soap*, xsd__anyType ***, const char*, const char*);
SOAP_FMAC3 xsd__anyType *** SOAP_FMAC4 soap_in_PointerToPointerToxsd__anyType(struct soap*, const char*, xsd__anyType ***, const char*);

#ifndef SOAP_TYPE_PointerToxsd__anyType
#define SOAP_TYPE_PointerToxsd__anyType (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__anyType(struct soap*, xsd__anyType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__anyType(struct soap*, xsd__anyType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__anyType(struct soap*, const char *, int, xsd__anyType *const*, const char *);
SOAP_FMAC3 xsd__anyType ** SOAP_FMAC4 soap_get_PointerToxsd__anyType(struct soap*, xsd__anyType **, const char*, const char*);
SOAP_FMAC3 xsd__anyType ** SOAP_FMAC4 soap_in_PointerToxsd__anyType(struct soap*, const char*, xsd__anyType **, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__DeviceStateVariable
#define SOAP_TYPE_PointerToPointerTons1__DeviceStateVariable (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__DeviceStateVariable(struct soap*, ns1__DeviceStateVariable **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__DeviceStateVariable(struct soap*, ns1__DeviceStateVariable **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__DeviceStateVariable(struct soap*, const char *, int, ns1__DeviceStateVariable **const*, const char *);
SOAP_FMAC3 ns1__DeviceStateVariable *** SOAP_FMAC4 soap_get_PointerToPointerTons1__DeviceStateVariable(struct soap*, ns1__DeviceStateVariable ***, const char*, const char*);
SOAP_FMAC3 ns1__DeviceStateVariable *** SOAP_FMAC4 soap_in_PointerToPointerTons1__DeviceStateVariable(struct soap*, const char*, ns1__DeviceStateVariable ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__DeviceStateVariable
#define SOAP_TYPE_PointerTons1__DeviceStateVariable (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__DeviceStateVariable(struct soap*, ns1__DeviceStateVariable *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__DeviceStateVariable(struct soap*, ns1__DeviceStateVariable *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__DeviceStateVariable(struct soap*, const char *, int, ns1__DeviceStateVariable *const*, const char *);
SOAP_FMAC3 ns1__DeviceStateVariable ** SOAP_FMAC4 soap_get_PointerTons1__DeviceStateVariable(struct soap*, ns1__DeviceStateVariable **, const char*, const char*);
SOAP_FMAC3 ns1__DeviceStateVariable ** SOAP_FMAC4 soap_in_PointerTons1__DeviceStateVariable(struct soap*, const char*, ns1__DeviceStateVariable **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__MessageEvent
#define SOAP_TYPE_PointerToPointerTons1__MessageEvent (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__MessageEvent(struct soap*, ns1__MessageEvent **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__MessageEvent(struct soap*, ns1__MessageEvent **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__MessageEvent(struct soap*, const char *, int, ns1__MessageEvent **const*, const char *);
SOAP_FMAC3 ns1__MessageEvent *** SOAP_FMAC4 soap_get_PointerToPointerTons1__MessageEvent(struct soap*, ns1__MessageEvent ***, const char*, const char*);
SOAP_FMAC3 ns1__MessageEvent *** SOAP_FMAC4 soap_in_PointerToPointerTons1__MessageEvent(struct soap*, const char*, ns1__MessageEvent ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__MessageEvent
#define SOAP_TYPE_PointerTons1__MessageEvent (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__MessageEvent(struct soap*, ns1__MessageEvent *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__MessageEvent(struct soap*, ns1__MessageEvent *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__MessageEvent(struct soap*, const char *, int, ns1__MessageEvent *const*, const char *);
SOAP_FMAC3 ns1__MessageEvent ** SOAP_FMAC4 soap_get_PointerTons1__MessageEvent(struct soap*, ns1__MessageEvent **, const char*, const char*);
SOAP_FMAC3 ns1__MessageEvent ** SOAP_FMAC4 soap_in_PointerTons1__MessageEvent(struct soap*, const char*, ns1__MessageEvent **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__DeviceState
#define SOAP_TYPE_PointerToPointerTons1__DeviceState (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__DeviceState(struct soap*, ns1__DeviceState **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__DeviceState(struct soap*, ns1__DeviceState **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__DeviceState(struct soap*, const char *, int, ns1__DeviceState **const*, const char *);
SOAP_FMAC3 ns1__DeviceState *** SOAP_FMAC4 soap_get_PointerToPointerTons1__DeviceState(struct soap*, ns1__DeviceState ***, const char*, const char*);
SOAP_FMAC3 ns1__DeviceState *** SOAP_FMAC4 soap_in_PointerToPointerTons1__DeviceState(struct soap*, const char*, ns1__DeviceState ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__DeviceState
#define SOAP_TYPE_PointerTons1__DeviceState (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__DeviceState(struct soap*, ns1__DeviceState *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__DeviceState(struct soap*, ns1__DeviceState *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__DeviceState(struct soap*, const char *, int, ns1__DeviceState *const*, const char *);
SOAP_FMAC3 ns1__DeviceState ** SOAP_FMAC4 soap_get_PointerTons1__DeviceState(struct soap*, ns1__DeviceState **, const char*, const char*);
SOAP_FMAC3 ns1__DeviceState ** SOAP_FMAC4 soap_in_PointerTons1__DeviceState(struct soap*, const char*, ns1__DeviceState **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfString
#define SOAP_TYPE_PointerToArrayOfString (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfString(struct soap*, ArrayOfString *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfString(struct soap*, ArrayOfString *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfString(struct soap*, const char *, int, ArrayOfString *const*, const char *);
SOAP_FMAC3 ArrayOfString ** SOAP_FMAC4 soap_get_PointerToArrayOfString(struct soap*, ArrayOfString **, const char*, const char*);
SOAP_FMAC3 ArrayOfString ** SOAP_FMAC4 soap_in_PointerToArrayOfString(struct soap*, const char*, ArrayOfString **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
